controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - moddifT_joint_rueda_izq
      - moddifT_joint_rueda_der
      - moddifD_joint_rueda_izq
      - moddifD_joint_rueda_der
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
